# app name & active profile
# distributed tracing : zipkin & sleuth sampling
spring:
  profiles:
    active: dev
  application:
    name: position-service
  config:
    import: optional:configserver:http://localhost:8888
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
    
# port & context path   
server:
  port: 8080
  servlet:
    context-path: /api
    
# k8s actuator probe
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
# logging level
logging:
  level:
    ROOT: INFO
    org.springframework.web: TRACE
    com.sapient.position: DEBUG