apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: country-service
  name: country-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: country-service
    spec:
      containers:
      - image: subhash06582/country-service:1.0.1
        imagePullPolicy: IfNotPresent
        name: country-service
        readinessProbe:
          httpGet:
            port: 8801
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8801
            path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: country-service
  name: country-service
  namespace: default
spec:
  ports:
  - port: 8801
    protocol: TCP
    targetPort: 8801
  selector:
    app: country-service
  sessionAffinity: None
  type: LoadBalancer