version: '3.7'

services:
  naming-server:
    container_name: naming-server
    build:
      context: ./naming-server
      dockerfile: Dockerfile
    image: subhash06582/naming-server
    ports: 
    - "8761:8761"
    environment:
    - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
    - eureka.server.waitTimeInMsWhenSyncEmpty=30000
    - eureka.server.peer-node-read-timeout-ms=30000
    - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    networks:
    - position-network
    
  
  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: subhash06582/config-server
    ports: 
    - "8888:8888"
    environment:
    - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
    depends_on:
    - "naming-server"
    networks:
    - position-network
    
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: subhash06582/api-gateway
    ports:
      - "8765:8765"
    environment:
    - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
    - SPRING_ZIPKIN_BASEURL=http://zipkin-server:9411/
    - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_ZIPKIN_SENDER_TYPE=rabbit
    depends_on:
    - "naming-server"
    - "config-server"
    - "rabbitmq"
    networks:
    - position-network
    
  country-service:
    container_name: country-service
    build:
      context: ./country-service
      dockerfile: Dockerfile
    image: subhash06582/country-service
    ports: 
    - "8801:8801"
    environment:
    - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
    - SPRING_ZIPKIN_BASEURL=http://zipkin-server:9411/
    - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_ZIPKIN_SENDER_TYPE=rabbit
    depends_on:
    - "naming-server"
    - "config-server"
    - "rabbitmq"
    networks:
    - position-network
    
  league-service:
    container_name: league-service
    build:
      context: ./league-service
      dockerfile: Dockerfile
    image: subhash06582/league-service
    ports: 
    - "8802:8802"
    environment:
    - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
    - SPRING_ZIPKIN_BASEURL=http://zipkin-server:9411/
    - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_ZIPKIN_SENDER_TYPE=rabbit
    depends_on:
    - "naming-server"
    - "config-server"
    - "rabbitmq"
    networks:
    - position-network
    
  standing-service:
    container_name: standing-service
    build:
      context: ./standing-service
      dockerfile: Dockerfile
    image: subhash06582/standing-service
    ports: 
    - "8803:8803"
    environment:
    - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
    - SPRING_ZIPKIN_BASEURL=http://zipkin-server:9411/
    - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_ZIPKIN_SENDER_TYPE=rabbit
    depends_on:
    - "naming-server"
    - "config-server"
    - "rabbitmq"
    networks:
    - position-network
  
  position-service:
    container_name: position-service
    build:
      context: ./position-service
      dockerfile: Dockerfile
    image: subhash06582/position-service
    ports:
    - "8080:8080"
    environment:
    - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
    - SPRING_PROFILES_ACTIVE=prod
    - SPRING_ZIPKIN_BASEURL=http://zipkin-server:9411/
    - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888/
    - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
    - SPRING_RABBITMQ_HOST=rabbitmq
    - SPRING_ZIPKIN_SENDER_TYPE=rabbit
    depends_on:
    - "naming-server"
    - "config-server"
    - "country-service"
    - "league-service"
    - "standing-service"
    - "rabbitmq"
    networks:
    - position-network
    
  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
    environment:
    - RABBIT_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
    - "rabbitmq"
    networks:
      - position-network
    restart: always #Restart if there is a problem starting up
    
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.5.3-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - position-network   
networks:
  position-network:
      
    
 # docker-compose build
 # docker-compose up -d // Builds, (re)creates, starts, and attaches to containers for a service
 # docker-compose down // Stops containers and removes containers, networks, volumes, and images created by up.
 # docker-compose rm
 # docker-compose ps
 # docker-compose top
 # docker-compose start
 # docker-compose stop
 # docker-compose logs <container name>
 # docker rm $(docker ps -aq)
 # docker run -p 9411:9411 openzipkin/zipkin:2.23