# app name & active profile
spring:
  profiles:
    active: dev
  application:
    name: naming-server
  config:
    import: optional:configserver:http://localhost:8888
    
eureka:
  instance:
      hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    
# port & context path   
server:
  port: 8761
  
# k8s actuator probe
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true