logging:
  level:
    ROOT: INFO
    org.springframework.web: TRACE
    com.sapient.gateway: DEBUG

eureka:
  instance:
      hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka