logging:
  level:
    ROOT: INFO
    org.springframework.web: TRACE
    com.sapient.standing: DEBUG

eureka:
  instance:
      hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
feign:
  apifootball:
    url: https://apiv2.apifootball.com/
    apiKey: 9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978